/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DichVuController;
import controller.NhaTroController;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DichVu;
import model.NhaTro;

/**
 *
 * @author nm204
 */
public class Home extends javax.swing.JFrame {
    NhaTroController nhaTroController;
    DichVuController dichVuController;
    DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
    /**
     * Creates new form Home
     */
    
    
    Color defaultColor, ClickedColor;
    public Home() {
        initComponents();
        defaultColor = new Color(13,36,51);
        ClickedColor = new Color(240,141,57);
        
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);
        
    }

    
    public void loadDataNhaTro()
    {
        nhaTroController = new NhaTroController();
        tblnhatro.setModel(defaultTableModel);
        setheaderNhaTro();
        setDataNhaTro(nhaTroController.sellectAll());
         tblnhatro.getTableHeader().setFont(new Font("Time New Roman", Font.BOLD, 16));
    }
    public void setheaderNhaTro()
    {
        defaultTableModel.setColumnCount(0);
        defaultTableModel.addColumn("Mã nhà trọ");
        defaultTableModel.addColumn("Tên nhà trọ");
        defaultTableModel.addColumn("Địa chỉ");
        defaultTableModel.addColumn("Số lượng phòng");
        defaultTableModel.addColumn("Ngày bắt đầu");
        defaultTableModel.addColumn("Trạng thái");
        defaultTableModel.addColumn("ID nhân viên");
    }
    public void setDataNhaTro(List<NhaTro> listnhatro)
    {
        defaultTableModel.setRowCount(0);
        for(NhaTro x : listnhatro)
        {
            defaultTableModel.addRow(new Object[]{x.getMaNhaTro(), x.getTenNhaTro(), x.getDiaChi(), x.getSoLuongPhong(),
                                                    x.getNgayBatDau(), x.getTrangThai(), x.getIdNhanVienQuanLy()});
        }
    }
    
    
    public void loadDataDichVu()
    {
        dichVuController = new DichVuController();
        DichVuTable.getTableHeader().setFont(new Font("Time New Roman", Font.BOLD, 16));
        DichVuTable.setModel(defaultTableModel);
        setheaderDichVu();
        setDataDichVu(dichVuController.sellectAll());
        DichVuTable.getTableHeader().setFont(new Font("Time New Roman", Font.BOLD, 16));
    }
    public void setheaderDichVu()
    {
        defaultTableModel.setColumnCount(0);
        defaultTableModel.addColumn("Mã dịch vụ");
        defaultTableModel.addColumn("Tên dịch vụ");
        defaultTableModel.addColumn("Giá");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Ngày bắt đầu");
        defaultTableModel.addColumn("Ngày kết thúc");
        defaultTableModel.addColumn("Trạng thái");
    }
    public void setDataDichVu(List<DichVu> listdichvu)
    {
        defaultTableModel.setRowCount(0);
        for(DichVu x : listdichvu){
            defaultTableModel.addRow(new Object[]{x.getMaDichVu(), x.getTenDichVu(), x.getGia(), x.getDonViTinh(), 
                x.getNgayBatDau(), x.getNgayKetThuc(), x.getTrangThai()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        NhaTro = new javax.swing.JPanel();
        NhaTroJframe = new javax.swing.JLabel();
        PhongTro = new javax.swing.JPanel();
        NhaTroJframe1 = new javax.swing.JLabel();
        tabtaisan = new javax.swing.JPanel();
        NhaTroJframe3 = new javax.swing.JLabel();
        tabdichvu = new javax.swing.JPanel();
        NhaTroJframe4 = new javax.swing.JLabel();
        HopDong = new javax.swing.JPanel();
        NhaTroJframe5 = new javax.swing.JLabel();
        NguoiChoThue = new javax.swing.JPanel();
        NhaTroJframe6 = new javax.swing.JLabel();
        BaoCao = new javax.swing.JPanel();
        NhaTroJframe7 = new javax.swing.JLabel();
        HoaDon = new javax.swing.JPanel();
        NhaTroJframe8 = new javax.swing.JLabel();
        list = new javax.swing.JPanel();
        taisan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nguoichothue = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hopdong = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        baocao = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        hoadon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nhatro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhatro = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        addNhaTro = new javax.swing.JLabel();
        btnSuaNhaTro = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        phongtro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dichvu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        themDichVuButton = new javax.swing.JButton();
        suaDichVuButton = new javax.swing.JButton();
        xoaDichVuButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DichVuTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(13, 36, 51));

        NhaTro.setBackground(new java.awt.Color(13, 36, 51));
        NhaTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NhaTroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NhaTroMousePressed(evt);
            }
        });

        NhaTroJframe.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe.setText("Nhà trọ");

        javax.swing.GroupLayout NhaTroLayout = new javax.swing.GroupLayout(NhaTro);
        NhaTro.setLayout(NhaTroLayout);
        NhaTroLayout.setHorizontalGroup(
            NhaTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaTroLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NhaTroLayout.setVerticalGroup(
            NhaTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NhaTroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        PhongTro.setBackground(new java.awt.Color(13, 36, 51));
        PhongTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhongTroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhongTroMousePressed(evt);
            }
        });

        NhaTroJframe1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe1.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe1.setText("Phòng trọ");

        javax.swing.GroupLayout PhongTroLayout = new javax.swing.GroupLayout(PhongTro);
        PhongTro.setLayout(PhongTroLayout);
        PhongTroLayout.setHorizontalGroup(
            PhongTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhongTroLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PhongTroLayout.setVerticalGroup(
            PhongTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhongTroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        tabtaisan.setBackground(new java.awt.Color(13, 36, 51));
        tabtaisan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabtaisanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabtaisanMousePressed(evt);
            }
        });

        NhaTroJframe3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe3.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe3.setText("Tài sản");

        javax.swing.GroupLayout tabtaisanLayout = new javax.swing.GroupLayout(tabtaisan);
        tabtaisan.setLayout(tabtaisanLayout);
        tabtaisanLayout.setHorizontalGroup(
            tabtaisanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabtaisanLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabtaisanLayout.setVerticalGroup(
            tabtaisanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabtaisanLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe3)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabdichvu.setBackground(new java.awt.Color(13, 36, 51));
        tabdichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabdichvuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabdichvuMousePressed(evt);
            }
        });

        NhaTroJframe4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe4.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe4.setText("Dịch vụ");

        javax.swing.GroupLayout tabdichvuLayout = new javax.swing.GroupLayout(tabdichvu);
        tabdichvu.setLayout(tabdichvuLayout);
        tabdichvuLayout.setHorizontalGroup(
            tabdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabdichvuLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabdichvuLayout.setVerticalGroup(
            tabdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabdichvuLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        HopDong.setBackground(new java.awt.Color(13, 36, 51));
        HopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HopDongMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HopDongMousePressed(evt);
            }
        });

        NhaTroJframe5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe5.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe5.setText("Hợp đồng");

        javax.swing.GroupLayout HopDongLayout = new javax.swing.GroupLayout(HopDong);
        HopDong.setLayout(HopDongLayout);
        HopDongLayout.setHorizontalGroup(
            HopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HopDongLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HopDongLayout.setVerticalGroup(
            HopDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HopDongLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe5)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        NguoiChoThue.setBackground(new java.awt.Color(13, 36, 51));
        NguoiChoThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NguoiChoThueMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NguoiChoThueMousePressed(evt);
            }
        });

        NhaTroJframe6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe6.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe6.setText("Người cho thuê");

        javax.swing.GroupLayout NguoiChoThueLayout = new javax.swing.GroupLayout(NguoiChoThue);
        NguoiChoThue.setLayout(NguoiChoThueLayout);
        NguoiChoThueLayout.setHorizontalGroup(
            NguoiChoThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguoiChoThueLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        NguoiChoThueLayout.setVerticalGroup(
            NguoiChoThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguoiChoThueLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe6)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        BaoCao.setBackground(new java.awt.Color(13, 36, 51));
        BaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaoCaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BaoCaoMousePressed(evt);
            }
        });

        NhaTroJframe7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe7.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe7.setText("Báo cáo");

        javax.swing.GroupLayout BaoCaoLayout = new javax.swing.GroupLayout(BaoCao);
        BaoCao.setLayout(BaoCaoLayout);
        BaoCaoLayout.setHorizontalGroup(
            BaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BaoCaoLayout.setVerticalGroup(
            BaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe7)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        HoaDon.setBackground(new java.awt.Color(13, 36, 51));
        HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDonMousePressed(evt);
            }
        });

        NhaTroJframe8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        NhaTroJframe8.setForeground(new java.awt.Color(255, 255, 255));
        NhaTroJframe8.setText("Hóa đơn");

        javax.swing.GroupLayout HoaDonLayout = new javax.swing.GroupLayout(HoaDon);
        HoaDon.setLayout(HoaDonLayout);
        HoaDonLayout.setHorizontalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(NhaTroJframe8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HoaDonLayout.setVerticalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(NhaTroJframe8)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NhaTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PhongTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabtaisan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabdichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HopDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NguoiChoThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabdichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(tabtaisan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HopDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NguoiChoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel2.setText("Tai San");

        javax.swing.GroupLayout taisanLayout = new javax.swing.GroupLayout(taisan);
        taisan.setLayout(taisanLayout);
        taisanLayout.setHorizontalGroup(
            taisanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taisanLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        taisanLayout.setVerticalGroup(
            taisanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taisanLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        jLabel3.setText("Nguoi Cho Thue");

        javax.swing.GroupLayout nguoichothueLayout = new javax.swing.GroupLayout(nguoichothue);
        nguoichothue.setLayout(nguoichothueLayout);
        nguoichothueLayout.setHorizontalGroup(
            nguoichothueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nguoichothueLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        nguoichothueLayout.setVerticalGroup(
            nguoichothueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nguoichothueLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel3)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        jLabel4.setText("Hop dong");

        javax.swing.GroupLayout hopdongLayout = new javax.swing.GroupLayout(hopdong);
        hopdong.setLayout(hopdongLayout);
        hopdongLayout.setHorizontalGroup(
            hopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopdongLayout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        hopdongLayout.setVerticalGroup(
            hopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopdongLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel4)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        jLabel5.setText("Bao Cao");

        javax.swing.GroupLayout baocaoLayout = new javax.swing.GroupLayout(baocao);
        baocao.setLayout(baocaoLayout);
        baocaoLayout.setHorizontalGroup(
            baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baocaoLayout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        baocaoLayout.setVerticalGroup(
            baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baocaoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel5)
                .addContainerGap(519, Short.MAX_VALUE))
        );

        jLabel6.setText("Hoa Don");

        javax.swing.GroupLayout hoadonLayout = new javax.swing.GroupLayout(hoadon);
        hoadon.setLayout(hoadonLayout);
        hoadonLayout.setHorizontalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoadonLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        hoadonLayout.setVerticalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoadonLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel6)
                .addContainerGap(511, Short.MAX_VALUE))
        );

        tblnhatro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblnhatro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblnhatro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblnhatro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblnhatro);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        addNhaTro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addNhaTro.setText("Thêm");
        addNhaTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNhaTrothemNhaTro(evt);
            }
        });

        btnSuaNhaTro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaNhaTro.setText("Sửa");
        btnSuaNhaTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaNhaTroMouseClicked(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btndelete.setText("Xóa");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(addNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(btnSuaNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNhaTro)
                    .addComponent(btnSuaNhaTro)
                    .addComponent(btndelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout nhatroLayout = new javax.swing.GroupLayout(nhatro);
        nhatro.setLayout(nhatroLayout);
        nhatroLayout.setHorizontalGroup(
            nhatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nhatroLayout.setVerticalGroup(
            nhatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Phong Tro");

        javax.swing.GroupLayout phongtroLayout = new javax.swing.GroupLayout(phongtro);
        phongtro.setLayout(phongtroLayout);
        phongtroLayout.setHorizontalGroup(
            phongtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phongtroLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        phongtroLayout.setVerticalGroup(
            phongtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phongtroLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        themDichVuButton.setBackground(new java.awt.Color(46, 145, 87));
        themDichVuButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        themDichVuButton.setText("Thêm");
        themDichVuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themDichVuButtonActionPerformed(evt);
            }
        });

        suaDichVuButton.setBackground(new java.awt.Color(46, 145, 87));
        suaDichVuButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        suaDichVuButton.setText("Sửa");
        suaDichVuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaDichVuButtonActionPerformed(evt);
            }
        });

        xoaDichVuButton.setBackground(new java.awt.Color(46, 145, 87));
        xoaDichVuButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        xoaDichVuButton.setText("Xóa ");
        xoaDichVuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaDichVuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(themDichVuButton)
                .addGap(177, 177, 177)
                .addComponent(suaDichVuButton)
                .addGap(153, 153, 153)
                .addComponent(xoaDichVuButton)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themDichVuButton)
                    .addComponent(suaDichVuButton)
                    .addComponent(xoaDichVuButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        DichVuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Giá", "Đơn vị tính", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DichVuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DichVuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(DichVuTable);

        javax.swing.GroupLayout dichvuLayout = new javax.swing.GroupLayout(dichvu);
        dichvu.setLayout(dichvuLayout);
        dichvuLayout.setHorizontalGroup(
            dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dichvuLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        dichvuLayout.setVerticalGroup(
            dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dichvuLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(taisan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(nguoichothue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(phongtro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(dichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(taisan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(nguoichothue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(phongtro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(dichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(ClickedColor);


    }//GEN-LAST:event_HoaDonMousePressed

    private void BaoCaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(ClickedColor);
        HoaDon.setBackground(defaultColor);


    }//GEN-LAST:event_BaoCaoMousePressed

    private void NguoiChoThueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NguoiChoThueMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(ClickedColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_NguoiChoThueMousePressed

    private void HopDongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HopDongMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(ClickedColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_HopDongMousePressed

    private void tabdichvuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabdichvuMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(ClickedColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_tabdichvuMousePressed

    private void tabdichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabdichvuMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(true);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        
        loadDataDichVu();
    }//GEN-LAST:event_tabdichvuMouseClicked

    private void tabtaisanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabtaisanMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(ClickedColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_tabtaisanMousePressed

    private void PhongTroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhongTroMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(defaultColor);
        PhongTro.setBackground(ClickedColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_PhongTroMousePressed

    private void NhaTroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaTroMousePressed
        // TODO add your handling code here:
        NhaTro.setBackground(ClickedColor);
        PhongTro.setBackground(defaultColor);
        tabtaisan.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        HopDong.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_NhaTroMousePressed

    private void NhaTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NhaTroMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(true);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        
        this.loadDataNhaTro();
    }//GEN-LAST:event_NhaTroMouseClicked

    private void PhongTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhongTroMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(true);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
    }//GEN-LAST:event_PhongTroMouseClicked

    private void tabtaisanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabtaisanMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(true);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
    }//GEN-LAST:event_tabtaisanMouseClicked

    private void HopDongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HopDongMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(true);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
    }//GEN-LAST:event_HopDongMouseClicked

    private void NguoiChoThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NguoiChoThueMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(true);
        baocao.setVisible(false);
        hoadon.setVisible(false);
    }//GEN-LAST:event_NguoiChoThueMouseClicked

    private void BaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(true);
        hoadon.setVisible(false);
    }//GEN-LAST:event_BaoCaoMouseClicked

    private void HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(true);
    }//GEN-LAST:event_HoaDonMouseClicked

    private void addNhaTrothemNhaTro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNhaTrothemNhaTro
        // TODO add your handling code here:
        ThemNhaTro nhatro = new ThemNhaTro(this);
        nhatro.setVisible(true);
        
    }//GEN-LAST:event_addNhaTrothemNhaTro

    private void btnSuaNhaTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNhaTroMouseClicked
        // TODO add your handling code here:
        int row = tblnhatro.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(Home.this , "Vui lòng chọn nhà trọ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String maNhaTro = String.valueOf(tblnhatro.getValueAt(row,0 ));
            new SuaNhaTro(maNhaTro).setVisible(true);
        }
    }//GEN-LAST:event_btnSuaNhaTroMouseClicked

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        // TODO add your handling code here:
        int row = tblnhatro.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(Home.this , "Vui lòng chọn nhà trọ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int confirm = JOptionPane.showConfirmDialog(Home.this, "Bạn chắc chắn muốn xóa không?");

            if(confirm == JOptionPane.YES_OPTION)
            {
                String maNhaTro = String.valueOf(tblnhatro.getValueAt(row,0 ));

                nhaTroController.DeleteMa(maNhaTro);
                defaultTableModel.setRowCount(0);
                setDataNhaTro(nhaTroController.sellectAll());
            }
        }
        this.loadDataNhaTro();
    }//GEN-LAST:event_btndeleteMouseClicked

    
    
    private void themDichVuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themDichVuButtonActionPerformed
        new ThemDichVu().setVisible(true);
    }//GEN-LAST:event_themDichVuButtonActionPerformed

    private void suaDichVuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaDichVuButtonActionPerformed
        // TODO add your handling code here:
        int row = DichVuTable.getSelectedRow();
        if(row == -1) {
            JOptionPane.showMessageDialog(Home.this, "Vui lòng chọn dịch vụ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String maDichVu = String.valueOf(DichVuTable.getValueAt(row, 0));
            new SuaDichVu(maDichVu).setVisible(true);
        }
    }//GEN-LAST:event_suaDichVuButtonActionPerformed

    private void xoaDichVuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaDichVuButtonActionPerformed
        // TODO add your handling code here:
        int row = DichVuTable.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(Home.this , "Vui lòng chọn dịch vụ cần xóa trước!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int confirm = JOptionPane.showConfirmDialog(Home.this, "Bạn chắc chắn muốn xóa không?");

            if(confirm == JOptionPane.YES_OPTION)
            {
                String maDichVu = String.valueOf(DichVuTable.getValueAt(row, 0));
                dichVuController.deleteDichVu(maDichVu);
                defaultTableModel.setRowCount(0);
                setDataDichVu(dichVuController.sellectAll());
            }
        }
        this.loadDataDichVu();
    }//GEN-LAST:event_xoaDichVuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BaoCao;
    private javax.swing.JTable DichVuTable;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JPanel HopDong;
    private javax.swing.JPanel NguoiChoThue;
    private javax.swing.JPanel NhaTro;
    private javax.swing.JLabel NhaTroJframe;
    private javax.swing.JLabel NhaTroJframe1;
    private javax.swing.JLabel NhaTroJframe3;
    private javax.swing.JLabel NhaTroJframe4;
    private javax.swing.JLabel NhaTroJframe5;
    private javax.swing.JLabel NhaTroJframe6;
    private javax.swing.JLabel NhaTroJframe7;
    private javax.swing.JLabel NhaTroJframe8;
    private javax.swing.JPanel PhongTro;
    private javax.swing.JLabel addNhaTro;
    private javax.swing.JPanel baocao;
    private javax.swing.JLabel btnSuaNhaTro;
    private javax.swing.JLabel btndelete;
    private javax.swing.JPanel dichvu;
    private javax.swing.JPanel hoadon;
    private javax.swing.JPanel hopdong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel list;
    private javax.swing.JPanel nguoichothue;
    private javax.swing.JPanel nhatro;
    private javax.swing.JPanel phongtro;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton suaDichVuButton;
    private javax.swing.JPanel tabdichvu;
    private javax.swing.JPanel tabtaisan;
    private javax.swing.JPanel taisan;
    private javax.swing.JTable tblnhatro;
    private javax.swing.JButton themDichVuButton;
    private javax.swing.JButton xoaDichVuButton;
    // End of variables declaration//GEN-END:variables
}
