/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DichVuController;
import controller.NhaTroController;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DichVu;
import model.NhaTro;

/**
 *
 * @author nm204
 */
public class Home extends javax.swing.JFrame {
    NhaTroController nhaTroController;
    DichVuController dichVuController;
    DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
    /**
     * Creates new form Home
     */
    
    
    Color defaultColor, ClickedColor, doneColor;
     public void loadDataNhaTro()
    {
        nhaTroController = new NhaTroController();
        tblnhatro.setModel(defaultTableModel);
        setheaderNhaTro();
        setDataNhaTro(nhaTroController.sellectAll());
        tblnhatro.getTableHeader().setFont(new Font("SansSefif", Font.PLAIN, 16));
        tblnhatro.getTableHeader().setBackground(doneColor);
        tblnhatro.setForeground(new Color(41, 41, 41));
    }
    public Home() {
        initComponents();
        defaultColor = new Color(255, 255, 255);
        ClickedColor = new Color(41, 98, 255);
        doneColor = new Color(0, 0, 0);
        motelLabel.setForeground(defaultColor);
        nhaTroPanel.setBackground(ClickedColor);
        //motelLabel.setForeground(doneColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);
        loadDataNhaTro();
        
    }

    
   
    public void setheaderNhaTro()
    {
        defaultTableModel.setColumnCount(0);
        defaultTableModel.addColumn("Mã nhà trọ");
        defaultTableModel.addColumn("Tên nhà trọ");
        defaultTableModel.addColumn("Địa chỉ");
        defaultTableModel.addColumn("Số lượng phòng");
        defaultTableModel.addColumn("Ngày bắt đầu");
        defaultTableModel.addColumn("Trạng thái");
        defaultTableModel.addColumn("ID nhân viên");
        
    }
    public void setDataNhaTro(List<NhaTro> listnhatro)
    {
        defaultTableModel.setRowCount(0);
        for(NhaTro x : listnhatro)
        {
            defaultTableModel.addRow(new Object[]{x.getMaNhaTro(), x.getTenNhaTro(), x.getDiaChi(), x.getSoLuongPhong(),
                                                    x.getNgayBatDau(), x.getTrangThai(), x.getIdNhanVienQuanLy()});
        }
    }
    
    
    public void loadDataDichVu()
    {
        dichVuController = new DichVuController();
        DichVuTable.getTableHeader().setFont(new Font("Time New Roman", Font.BOLD, 16));
        DichVuTable.setModel(defaultTableModel);
        setheaderDichVu();
        setDataDichVu(dichVuController.sellectAll());
        DichVuTable.getTableHeader().setFont(new Font("Time New Roman", Font.BOLD, 16));
    }
    public void setheaderDichVu()
    {
        defaultTableModel.setColumnCount(0);
        defaultTableModel.addColumn("Mã dịch vụ");
        defaultTableModel.addColumn("Tên dịch vụ");
        defaultTableModel.addColumn("Giá");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Ngày bắt đầu");
        defaultTableModel.addColumn("Ngày kết thúc");
        defaultTableModel.addColumn("Trạng thái");
    }
    public void setDataDichVu(List<DichVu> listdichvu)
    {
        defaultTableModel.setRowCount(0);
        for(DichVu x : listdichvu){
            defaultTableModel.addRow(new Object[]{x.getMaDichVu(), x.getTenDichVu(), x.getGia(), x.getDonViTinh(), 
                x.getNgayBatDau(), x.getNgayKetThuc(), x.getTrangThai()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        nhaTroPanel = new javax.swing.JPanel();
        motelLabel = new javax.swing.JLabel();
        PhongTro = new javax.swing.JPanel();
        houseLabel = new javax.swing.JLabel();
        t = new javax.swing.JPanel();
        assetLabel = new javax.swing.JLabel();
        tabdichvu = new javax.swing.JPanel();
        seviceLabel = new javax.swing.JLabel();
        hopDongPanel = new javax.swing.JPanel();
        contractLabel = new javax.swing.JLabel();
        NguoiChoThue = new javax.swing.JPanel();
        renterLabel = new javax.swing.JLabel();
        BaoCao = new javax.swing.JPanel();
        reportLabel = new javax.swing.JLabel();
        HoaDon = new javax.swing.JPanel();
        billLabel = new javax.swing.JLabel();
        list = new javax.swing.JPanel();
        taisan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nguoichothue = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        hopdong = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        baocao = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        hoadon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nhatro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhatro = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        addNhaTro = new javax.swing.JLabel();
        btnSuaNhaTro = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        phongtro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dichvu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        themDichVuButton = new javax.swing.JButton();
        suaDichVuButton = new javax.swing.JButton();
        xoaDichVuButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        DichVuTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebar.setBackground(new java.awt.Color(255, 255, 255));

        nhaTroPanel.setBackground(new java.awt.Color(255, 255, 255));
        nhaTroPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhaTroPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nhaTroPanelMousePressed(evt);
            }
        });

        motelLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        motelLabel.setForeground(new java.awt.Color(51, 51, 51));
        motelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hotel.png"))); // NOI18N
        motelLabel.setText("Nhà trọ");

        javax.swing.GroupLayout nhaTroPanelLayout = new javax.swing.GroupLayout(nhaTroPanel);
        nhaTroPanel.setLayout(nhaTroPanelLayout);
        nhaTroPanelLayout.setHorizontalGroup(
            nhaTroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhaTroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(motelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        nhaTroPanelLayout.setVerticalGroup(
            nhaTroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhaTroPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(motelLabel)
                .addContainerGap())
        );

        PhongTro.setBackground(new java.awt.Color(255, 255, 255));
        PhongTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PhongTroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PhongTroMousePressed(evt);
            }
        });

        houseLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        houseLabel.setForeground(new java.awt.Color(51, 51, 51));
        houseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/room.png"))); // NOI18N
        houseLabel.setText("Phòng trọ");

        javax.swing.GroupLayout PhongTroLayout = new javax.swing.GroupLayout(PhongTro);
        PhongTro.setLayout(PhongTroLayout);
        PhongTroLayout.setHorizontalGroup(
            PhongTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhongTroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(houseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PhongTroLayout.setVerticalGroup(
            PhongTroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PhongTroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(houseLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        t.setBackground(new java.awt.Color(255, 255, 255));
        t.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tMousePressed(evt);
            }
        });

        assetLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        assetLabel.setForeground(new java.awt.Color(51, 51, 51));
        assetLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/asset.png"))); // NOI18N
        assetLabel.setText("Tài sản");

        javax.swing.GroupLayout tLayout = new javax.swing.GroupLayout(t);
        t.setLayout(tLayout);
        tLayout.setHorizontalGroup(
            tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tLayout.setVerticalGroup(
            tLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(assetLabel)
                .addContainerGap())
        );

        tabdichvu.setBackground(new java.awt.Color(255, 255, 255));
        tabdichvu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabdichvuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabdichvuMousePressed(evt);
            }
        });

        seviceLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        seviceLabel.setForeground(new java.awt.Color(51, 51, 51));
        seviceLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/sevice.png"))); // NOI18N
        seviceLabel.setText("Dịch vụ");

        javax.swing.GroupLayout tabdichvuLayout = new javax.swing.GroupLayout(tabdichvu);
        tabdichvu.setLayout(tabdichvuLayout);
        tabdichvuLayout.setHorizontalGroup(
            tabdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabdichvuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabdichvuLayout.setVerticalGroup(
            tabdichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabdichvuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seviceLabel)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        hopDongPanel.setBackground(new java.awt.Color(255, 255, 255));
        hopDongPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hopDongPanelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                hopDongPanelMousePressed(evt);
            }
        });

        contractLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        contractLabel.setForeground(new java.awt.Color(51, 51, 51));
        contractLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/contract.png"))); // NOI18N
        contractLabel.setText("Hợp đồng");

        javax.swing.GroupLayout hopDongPanelLayout = new javax.swing.GroupLayout(hopDongPanel);
        hopDongPanel.setLayout(hopDongPanelLayout);
        hopDongPanelLayout.setHorizontalGroup(
            hopDongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopDongPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contractLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        hopDongPanelLayout.setVerticalGroup(
            hopDongPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hopDongPanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(contractLabel)
                .addContainerGap())
        );

        NguoiChoThue.setBackground(new java.awt.Color(255, 255, 255));
        NguoiChoThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NguoiChoThueMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NguoiChoThueMousePressed(evt);
            }
        });

        renterLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        renterLabel.setForeground(new java.awt.Color(51, 51, 51));
        renterLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/renter.png"))); // NOI18N
        renterLabel.setText("Người cho thuê");

        javax.swing.GroupLayout NguoiChoThueLayout = new javax.swing.GroupLayout(NguoiChoThue);
        NguoiChoThue.setLayout(NguoiChoThueLayout);
        NguoiChoThueLayout.setHorizontalGroup(
            NguoiChoThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NguoiChoThueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(renterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
        NguoiChoThueLayout.setVerticalGroup(
            NguoiChoThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NguoiChoThueLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(renterLabel)
                .addContainerGap())
        );

        BaoCao.setBackground(new java.awt.Color(255, 255, 255));
        BaoCao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BaoCaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BaoCaoMousePressed(evt);
            }
        });

        reportLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        reportLabel.setForeground(new java.awt.Color(51, 51, 51));
        reportLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/report.png"))); // NOI18N
        reportLabel.setText("Báo cáo");

        javax.swing.GroupLayout BaoCaoLayout = new javax.swing.GroupLayout(BaoCao);
        BaoCao.setLayout(BaoCaoLayout);
        BaoCaoLayout.setHorizontalGroup(
            BaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BaoCaoLayout.setVerticalGroup(
            BaoCaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BaoCaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportLabel)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        HoaDon.setBackground(new java.awt.Color(255, 255, 255));
        HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HoaDonMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HoaDonMousePressed(evt);
            }
        });

        billLabel.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        billLabel.setForeground(new java.awt.Color(51, 51, 51));
        billLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        billLabel.setText("Hóa đơn");

        javax.swing.GroupLayout HoaDonLayout = new javax.swing.GroupLayout(HoaDon);
        HoaDon.setLayout(HoaDonLayout);
        HoaDonLayout.setHorizontalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        HoaDonLayout.setVerticalGroup(
            HoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(billLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NguoiChoThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hopDongPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(t, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tabdichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PhongTro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nhaTroPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(nhaTroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PhongTro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabdichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hopDongPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(NguoiChoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Tai San");

        javax.swing.GroupLayout taisanLayout = new javax.swing.GroupLayout(taisan);
        taisan.setLayout(taisanLayout);
        taisanLayout.setHorizontalGroup(
            taisanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taisanLayout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
        );
        taisanLayout.setVerticalGroup(
            taisanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taisanLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabel2)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        jLabel3.setText("Nguoi Cho Thue");

        javax.swing.GroupLayout nguoichothueLayout = new javax.swing.GroupLayout(nguoichothue);
        nguoichothue.setLayout(nguoichothueLayout);
        nguoichothueLayout.setHorizontalGroup(
            nguoichothueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nguoichothueLayout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(437, Short.MAX_VALUE))
        );
        nguoichothueLayout.setVerticalGroup(
            nguoichothueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nguoichothueLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel3)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        jLabel4.setText("Hop dong");

        javax.swing.GroupLayout hopdongLayout = new javax.swing.GroupLayout(hopdong);
        hopdong.setLayout(hopdongLayout);
        hopdongLayout.setHorizontalGroup(
            hopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopdongLayout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        hopdongLayout.setVerticalGroup(
            hopdongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopdongLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel4)
                .addContainerGap(498, Short.MAX_VALUE))
        );

        jLabel5.setText("Bao Cao");

        javax.swing.GroupLayout baocaoLayout = new javax.swing.GroupLayout(baocao);
        baocao.setLayout(baocaoLayout);
        baocaoLayout.setHorizontalGroup(
            baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baocaoLayout.createSequentialGroup()
                .addGap(427, 427, 427)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(444, Short.MAX_VALUE))
        );
        baocaoLayout.setVerticalGroup(
            baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baocaoLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel5)
                .addContainerGap(519, Short.MAX_VALUE))
        );

        jLabel6.setText("Hoa Don");

        javax.swing.GroupLayout hoadonLayout = new javax.swing.GroupLayout(hoadon);
        hoadon.setLayout(hoadonLayout);
        hoadonLayout.setHorizontalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoadonLayout.createSequentialGroup()
                .addGap(394, 394, 394)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(488, Short.MAX_VALUE))
        );
        hoadonLayout.setVerticalGroup(
            hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoadonLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jLabel6)
                .addContainerGap(511, Short.MAX_VALUE))
        );

        tblnhatro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblnhatro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblnhatro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblnhatro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblnhatro);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        addNhaTro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addNhaTro.setText("Thêm");
        addNhaTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNhaTrothemNhaTro(evt);
            }
        });

        btnSuaNhaTro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaNhaTro.setText("Sửa");
        btnSuaNhaTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaNhaTroMouseClicked(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btndelete.setText("Xóa");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(addNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addComponent(btnSuaNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNhaTro)
                    .addComponent(btnSuaNhaTro)
                    .addComponent(btndelete))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout nhatroLayout = new javax.swing.GroupLayout(nhatro);
        nhatro.setLayout(nhatroLayout);
        nhatroLayout.setHorizontalGroup(
            nhatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nhatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        nhatroLayout.setVerticalGroup(
            nhatroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nhatroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Phong Tro");

        javax.swing.GroupLayout phongtroLayout = new javax.swing.GroupLayout(phongtro);
        phongtro.setLayout(phongtroLayout);
        phongtroLayout.setHorizontalGroup(
            phongtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phongtroLayout.createSequentialGroup()
                .addGap(409, 409, 409)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(450, Short.MAX_VALUE))
        );
        phongtroLayout.setVerticalGroup(
            phongtroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phongtroLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLabel1)
                .addContainerGap(488, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        themDichVuButton.setBackground(new java.awt.Color(46, 145, 87));
        themDichVuButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        themDichVuButton.setText("Thêm");
        themDichVuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themDichVuButtonActionPerformed(evt);
            }
        });

        suaDichVuButton.setBackground(new java.awt.Color(46, 145, 87));
        suaDichVuButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        suaDichVuButton.setText("Sửa");
        suaDichVuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaDichVuButtonActionPerformed(evt);
            }
        });

        xoaDichVuButton.setBackground(new java.awt.Color(46, 145, 87));
        xoaDichVuButton.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        xoaDichVuButton.setText("Xóa ");
        xoaDichVuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaDichVuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(themDichVuButton)
                .addGap(177, 177, 177)
                .addComponent(suaDichVuButton)
                .addGap(153, 153, 153)
                .addComponent(xoaDichVuButton)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themDichVuButton)
                    .addComponent(suaDichVuButton)
                    .addComponent(xoaDichVuButton))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        DichVuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Giá", "Đơn vị tính", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DichVuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        DichVuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(DichVuTable);

        javax.swing.GroupLayout dichvuLayout = new javax.swing.GroupLayout(dichvu);
        dichvu.setLayout(dichvuLayout);
        dichvuLayout.setHorizontalGroup(
            dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(dichvuLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        dichvuLayout.setVerticalGroup(
            dichvuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dichvuLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout listLayout = new javax.swing.GroupLayout(list);
        list.setLayout(listLayout);
        listLayout.setHorizontalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(taisan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(nguoichothue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(phongtro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(dichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        listLayout.setVerticalGroup(
            listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhatro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(taisan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(nguoichothue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(phongtro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(listLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(dichvu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(ClickedColor);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        hopDongPanel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(defaultColor);
        


    }//GEN-LAST:event_HoaDonMousePressed

    private void BaoCaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(ClickedColor);
        HoaDon.setBackground(defaultColor);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        hopDongPanel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(defaultColor);
        billLabel.setForeground(doneColor);
        


    }//GEN-LAST:event_BaoCaoMousePressed

    private void NguoiChoThueMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NguoiChoThueMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(ClickedColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(defaultColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
        

    }//GEN-LAST:event_NguoiChoThueMousePressed

    private void hopDongPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hopDongPanelMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(ClickedColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        hopDongPanel.setForeground(defaultColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);

    }//GEN-LAST:event_hopDongPanelMousePressed

    private void tabdichvuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabdichvuMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(ClickedColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(defaultColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
        
    }//GEN-LAST:event_tabdichvuMousePressed

    private void tabdichvuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabdichvuMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(true);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(defaultColor);
        assetLabel.setForeground(doneColor);
        hopDongPanel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
        loadDataDichVu();
    }//GEN-LAST:event_tabdichvuMouseClicked

    private void tMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(defaultColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(ClickedColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_tMousePressed

    private void PhongTroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhongTroMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(defaultColor);
        PhongTro.setBackground(ClickedColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);

    }//GEN-LAST:event_PhongTroMousePressed

    private void nhaTroPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhaTroPanelMousePressed
        // TODO add your handling code here:
        nhaTroPanel.setBackground(ClickedColor);
        PhongTro.setBackground(defaultColor);
        t.setBackground(defaultColor);
        tabdichvu.setBackground(defaultColor);
        hopDongPanel.setBackground(defaultColor);
        NguoiChoThue.setBackground(defaultColor);
        BaoCao.setBackground(defaultColor);
        HoaDon.setBackground(defaultColor);
        motelLabel.setForeground(defaultColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        hopDongPanel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
       
        

    }//GEN-LAST:event_nhaTroPanelMousePressed

    private void nhaTroPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhaTroPanelMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(true);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        motelLabel.setForeground(defaultColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
        this.loadDataNhaTro();
    }//GEN-LAST:event_nhaTroPanelMouseClicked

    private void PhongTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PhongTroMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(true);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(defaultColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
    }//GEN-LAST:event_PhongTroMouseClicked

    private void tMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(true);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(defaultColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
    }//GEN-LAST:event_tMouseClicked

    private void hopDongPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hopDongPanelMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(true);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(defaultColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
    }//GEN-LAST:event_hopDongPanelMouseClicked

    private void NguoiChoThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NguoiChoThueMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(true);
        baocao.setVisible(false);
        hoadon.setVisible(false);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(defaultColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(doneColor);
    }//GEN-LAST:event_NguoiChoThueMouseClicked

    private void BaoCaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BaoCaoMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(true);
        hoadon.setVisible(false);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(defaultColor);
        billLabel.setForeground(doneColor);
    }//GEN-LAST:event_BaoCaoMouseClicked

    private void HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HoaDonMouseClicked
        // TODO add your handling code here:
        nhatro.setVisible(false);
        phongtro.setVisible(false);
        dichvu.setVisible(false);
        taisan.setVisible(false);
        hopdong.setVisible(false);
        nguoichothue.setVisible(false);
        baocao.setVisible(false);
        hoadon.setVisible(true);
        motelLabel.setForeground(doneColor);
        houseLabel.setForeground(doneColor);
        seviceLabel.setForeground(doneColor);
        assetLabel.setForeground(doneColor);
        contractLabel.setForeground(doneColor);
        renterLabel.setForeground(doneColor);
        reportLabel.setForeground(doneColor);
        billLabel.setForeground(defaultColor);
    }//GEN-LAST:event_HoaDonMouseClicked

    
    
    private void themDichVuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themDichVuButtonActionPerformed
        new ThemDichVu().setVisible(true);
    }//GEN-LAST:event_themDichVuButtonActionPerformed

    private void suaDichVuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaDichVuButtonActionPerformed
        // TODO add your handling code here:
        int row = DichVuTable.getSelectedRow();
        if(row == -1) {
            JOptionPane.showMessageDialog(Home.this, "Vui lòng chọn dịch vụ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            String maDichVu = String.valueOf(DichVuTable.getValueAt(row, 0));
            new SuaDichVu(maDichVu).setVisible(true);
        }
    }//GEN-LAST:event_suaDichVuButtonActionPerformed

    private void xoaDichVuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaDichVuButtonActionPerformed
        // TODO add your handling code here:
        int row = DichVuTable.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(Home.this , "Vui lòng chọn dịch vụ cần xóa trước!", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int confirm = JOptionPane.showConfirmDialog(Home.this, "Bạn chắc chắn muốn xóa không?");

            if(confirm == JOptionPane.YES_OPTION)
            {
                String maDichVu = String.valueOf(DichVuTable.getValueAt(row, 0));
                dichVuController.deleteDichVu(maDichVu);
                defaultTableModel.setRowCount(0);
                setDataDichVu(dichVuController.sellectAll());
            }
        }
        this.loadDataDichVu();
    }//GEN-LAST:event_xoaDichVuButtonActionPerformed

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        // TODO add your handling code here:
        int row = tblnhatro.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(Home.this , "Vui lòng chọn nhà trọ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int confirm = JOptionPane.showConfirmDialog(Home.this, "Bạn chắc chắn muốn xóa không?");

            if(confirm == JOptionPane.YES_OPTION)
            {
                String maNhaTro = String.valueOf(tblnhatro.getValueAt(row,0 ));

                nhaTroController.DeleteMa(maNhaTro);
                defaultTableModel.setRowCount(0);
                setDataNhaTro(nhaTroController.sellectAll());
            }
        }
        this.loadDataNhaTro();
    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnSuaNhaTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNhaTroMouseClicked
        // TODO add your handling code here:
        int row = tblnhatro.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(Home.this , "Vui lòng chọn nhà trọ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            String maNhaTro = String.valueOf(tblnhatro.getValueAt(row,0 ));
            new SuaNhaTro(maNhaTro).setVisible(true);
        }
    }//GEN-LAST:event_btnSuaNhaTroMouseClicked

    private void addNhaTrothemNhaTro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNhaTrothemNhaTro
        // TODO add your handling code here:
        ThemNhaTro nhatro = new ThemNhaTro(this);
        nhatro.setVisible(true);

    }//GEN-LAST:event_addNhaTrothemNhaTro

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BaoCao;
    private javax.swing.JTable DichVuTable;
    private javax.swing.JPanel HoaDon;
    private javax.swing.JPanel NguoiChoThue;
    private javax.swing.JPanel PhongTro;
    private javax.swing.JLabel addNhaTro;
    private javax.swing.JLabel assetLabel;
    private javax.swing.JPanel baocao;
    private javax.swing.JLabel billLabel;
    private javax.swing.JLabel btnSuaNhaTro;
    private javax.swing.JLabel btndelete;
    private javax.swing.JLabel contractLabel;
    private javax.swing.JPanel dichvu;
    private javax.swing.JPanel hoadon;
    private javax.swing.JPanel hopDongPanel;
    private javax.swing.JPanel hopdong;
    private javax.swing.JLabel houseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel list;
    private javax.swing.JLabel motelLabel;
    private javax.swing.JPanel nguoichothue;
    private javax.swing.JPanel nhaTroPanel;
    private javax.swing.JPanel nhatro;
    private javax.swing.JPanel phongtro;
    private javax.swing.JLabel renterLabel;
    private javax.swing.JLabel reportLabel;
    private javax.swing.JLabel seviceLabel;
    private javax.swing.JPanel sidebar;
    private javax.swing.JButton suaDichVuButton;
    private javax.swing.JPanel t;
    private javax.swing.JPanel tabdichvu;
    private javax.swing.JPanel taisan;
    private javax.swing.JTable tblnhatro;
    private javax.swing.JButton themDichVuButton;
    private javax.swing.JButton xoaDichVuButton;
    // End of variables declaration//GEN-END:variables
}
