/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.NhaTroController;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhaTro;

/**
 *
 * @author nm204
 */
public class NhaTroView extends javax.swing.JFrame {
    NhaTroController nhaTroController;
    
    DefaultTableModel defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
            
        };
    /**
     * Creates new form NhaTro
     */
    public NhaTroView()  {
       
        initComponents();
        nhaTroController = new NhaTroController();
        
        
        tblnhatro.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã nhà trọ");
        defaultTableModel.addColumn("Tên nhà trọ");
        defaultTableModel.addColumn("Địa chỉ");
        defaultTableModel.addColumn("Số lượng phòng");
        defaultTableModel.addColumn("Ngày bắt đầu");
        defaultTableModel.addColumn("Trạng thái");
        defaultTableModel.addColumn("ID nhân viên");
        
        setData(nhaTroController.sellectAll());
         tblnhatro.getTableHeader().setFont(new Font("Time New Roman", Font.BOLD, 16));
    }
    public void setData(List<NhaTro> listnhatro)
    {
        for(NhaTro x : listnhatro)
        {
            defaultTableModel.addRow(new Object[]{x.getMaNhaTro(), x.getTenNhaTro(), x.getDiaChi(), x.getSoLuongPhong(),
                                                    x.getNgayBatDau(), x.getTrangThai(), x.getIdNhanVienQuanLy()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnhatro = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        addNhaTro = new javax.swing.JLabel();
        btnSuaNhaTro = new javax.swing.JLabel();
        btndelete = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        nhaTroLabel1 = new javax.swing.JLabel();
        phongTroTab = new javax.swing.JPanel();
        phongTroLabel = new javax.swing.JLabel();
        dichVuTab = new javax.swing.JPanel();
        dichVuLabel = new javax.swing.JLabel();
        hopDongTab = new javax.swing.JPanel();
        hopDongLabel = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        taiSanTab = new javax.swing.JPanel();
        taiSanLabel = new javax.swing.JLabel();
        nguoiChoThueTab = new javax.swing.JPanel();
        nguoiChoThueLabel = new javax.swing.JLabel();
        baoCaoTab = new javax.swing.JPanel();
        baoCaoLabel = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        hoaDonTab = new javax.swing.JPanel();
        hoaDonLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 205, 50), 3, true));
        jPanel3.setForeground(new java.awt.Color(255, 204, 204));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 205, 50), 3, true));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setText("Danh sách nhà trọ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        tblnhatro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblnhatro.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblnhatro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblnhatro.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblnhatro);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1098, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 18))); // NOI18N

        addNhaTro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        addNhaTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_40px.png"))); // NOI18N
        addNhaTro.setText("Thêm");
        addNhaTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                themNhaTro(evt);
            }
        });

        btnSuaNhaTro.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSuaNhaTro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_40px.png"))); // NOI18N
        btnSuaNhaTro.setText("Sửa");
        btnSuaNhaTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaNhaTroMouseClicked(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_40px.png"))); // NOI18N
        btndelete.setText("Xóa");
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(addNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(btnSuaNhaTro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addNhaTro)
                    .addComponent(btnSuaNhaTro)
                    .addComponent(btndelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        nhaTroLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nhaTroLabel1.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\house.png")); // NOI18N
        nhaTroLabel1.setText("Nhà trọ");
        nhaTroLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhaTroLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(nhaTroLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nhaTroLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        phongTroTab.setBackground(new java.awt.Color(255, 255, 255));

        phongTroLabel.setBackground(new java.awt.Color(255, 255, 255));
        phongTroLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        phongTroLabel.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\bed.png")); // NOI18N
        phongTroLabel.setText("Phòng trọ");
        phongTroLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phongTroLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout phongTroTabLayout = new javax.swing.GroupLayout(phongTroTab);
        phongTroTab.setLayout(phongTroTabLayout);
        phongTroTabLayout.setHorizontalGroup(
            phongTroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phongTroTabLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(phongTroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        phongTroTabLayout.setVerticalGroup(
            phongTroTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(phongTroTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phongTroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        dichVuTab.setBackground(new java.awt.Color(255, 255, 255));
        dichVuTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dichVuTabMouseClicked(evt);
            }
        });

        dichVuLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        dichVuLabel.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\customer-service.png")); // NOI18N
        dichVuLabel.setText("Dịch vụ");

        javax.swing.GroupLayout dichVuTabLayout = new javax.swing.GroupLayout(dichVuTab);
        dichVuTab.setLayout(dichVuTabLayout);
        dichVuTabLayout.setHorizontalGroup(
            dichVuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dichVuTabLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(dichVuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        dichVuTabLayout.setVerticalGroup(
            dichVuTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dichVuTabLayout.createSequentialGroup()
                .addComponent(dichVuLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        hopDongTab.setBackground(new java.awt.Color(255, 255, 255));

        hopDongLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hopDongLabel.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\contract.png")); // NOI18N
        hopDongLabel.setText("Hợp đồng");

        javax.swing.GroupLayout hopDongTabLayout = new javax.swing.GroupLayout(hopDongTab);
        hopDongTab.setLayout(hopDongTabLayout);
        hopDongTabLayout.setHorizontalGroup(
            hopDongTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopDongTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(hopDongLabel)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        hopDongTabLayout.setVerticalGroup(
            hopDongTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hopDongTabLayout.createSequentialGroup()
                .addComponent(hopDongLabel)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );

        taiSanTab.setBackground(new java.awt.Color(255, 255, 255));

        taiSanLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        taiSanLabel.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\fixed-asset.png")); // NOI18N
        taiSanLabel.setText("Tài sản");

        javax.swing.GroupLayout taiSanTabLayout = new javax.swing.GroupLayout(taiSanTab);
        taiSanTab.setLayout(taiSanTabLayout);
        taiSanTabLayout.setHorizontalGroup(
            taiSanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiSanTabLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(taiSanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        taiSanTabLayout.setVerticalGroup(
            taiSanTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taiSanTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taiSanLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        nguoiChoThueTab.setBackground(new java.awt.Color(255, 255, 255));

        nguoiChoThueLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nguoiChoThueLabel.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\team.png")); // NOI18N
        nguoiChoThueLabel.setText("Người cho thuê");
        nguoiChoThueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nguoiChoThueLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout nguoiChoThueTabLayout = new javax.swing.GroupLayout(nguoiChoThueTab);
        nguoiChoThueTab.setLayout(nguoiChoThueTabLayout);
        nguoiChoThueTabLayout.setHorizontalGroup(
            nguoiChoThueTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nguoiChoThueTabLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(nguoiChoThueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        nguoiChoThueTabLayout.setVerticalGroup(
            nguoiChoThueTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nguoiChoThueTabLayout.createSequentialGroup()
                .addComponent(nguoiChoThueLabel)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        baoCaoTab.setBackground(new java.awt.Color(255, 255, 255));

        baoCaoLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        baoCaoLabel.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\seo-report.png")); // NOI18N
        baoCaoLabel.setText("Báo cáo");

        javax.swing.GroupLayout baoCaoTabLayout = new javax.swing.GroupLayout(baoCaoTab);
        baoCaoTab.setLayout(baoCaoTabLayout);
        baoCaoTabLayout.setHorizontalGroup(
            baoCaoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baoCaoTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(baoCaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        baoCaoTabLayout.setVerticalGroup(
            baoCaoTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baoCaoTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(baoCaoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        hoaDonTab.setBackground(new java.awt.Color(255, 255, 255));

        hoaDonLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        hoaDonLabel.setIcon(new javax.swing.ImageIcon("D:\\Study\\TTCN\\quanlynhatro_nhom\\quanlynhatro\\src\\main\\resources\\icon\\bill.png")); // NOI18N
        hoaDonLabel.setText("Hóa đơn");

        javax.swing.GroupLayout hoaDonTabLayout = new javax.swing.GroupLayout(hoaDonTab);
        hoaDonTab.setLayout(hoaDonTabLayout);
        hoaDonTabLayout.setHorizontalGroup(
            hoaDonTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDonTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(hoaDonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        hoaDonTabLayout.setVerticalGroup(
            hoaDonTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoaDonTabLayout.createSequentialGroup()
                .addComponent(hoaDonLabel)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(phongTroTab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dichVuTab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(baoCaoTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nguoiChoThueTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hopDongTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taiSanTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(hoaDonTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(phongTroTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dichVuTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(taiSanTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(hopDongTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nguoiChoThueTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(baoCaoTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(hoaDonTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(402, 402, 402)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void themNhaTro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_themNhaTro
        // TODO add your handling code here:
        new ThemNhaTro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_themNhaTro

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        // TODO add your handling code here:
        int row = tblnhatro.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(NhaTroView.this , "Vui lòng chọn nhà trọ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            int confirm = JOptionPane.showConfirmDialog(NhaTroView.this, "Bạn chắc chắn muốn xóa không?");
            
            if(confirm == JOptionPane.YES_OPTION)
            {
                String maNhaTro = String.valueOf(tblnhatro.getValueAt(row,0 ));
                
                nhaTroController.DeleteMa(maNhaTro);
                defaultTableModel.setRowCount(0);
                setData(nhaTroController.sellectAll());
            }
        }
    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnSuaNhaTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaNhaTroMouseClicked
        // TODO add your handling code here:
        int row = tblnhatro.getSelectedRow();
        if(row == -1)
        {
            JOptionPane.showMessageDialog(NhaTroView.this , "Vui lòng chọn nhà trọ trước", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        else
        {  
            String maNhaTro = String.valueOf(tblnhatro.getValueAt(row,0 ));
            new SuaNhaTro(maNhaTro).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSuaNhaTroMouseClicked

    private void nhaTroLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhaTroLabel1MouseClicked
        // TODO add your handling code here:
//        this.setActiveTab("nhatro");
//        new NhaTroView().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_nhaTroLabel1MouseClicked

    private void phongTroLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phongTroLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phongTroLabelMouseClicked

    private void dichVuTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dichVuTabMouseClicked
        // TODO add your handling code here:
//        this.setActiveTab("dichvu");
//        new DanhSachDichVu().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_dichVuTabMouseClicked

    private void nguoiChoThueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nguoiChoThueLabelMouseClicked
        // TODO add your handling code here:
//        this.setActiveTab("nguoithue");
//        new DanhSachNguoiThue().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_nguoiChoThueLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhaTroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhaTroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhaTroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhaTroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhaTroView().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addNhaTro;
    private javax.swing.JLabel baoCaoLabel;
    private javax.swing.JPanel baoCaoTab;
    private javax.swing.JLabel btnSuaNhaTro;
    private javax.swing.JLabel btndelete;
    private javax.swing.JLabel dichVuLabel;
    private javax.swing.JPanel dichVuTab;
    private javax.swing.JLabel hoaDonLabel;
    private javax.swing.JPanel hoaDonTab;
    private javax.swing.JLabel hopDongLabel;
    private javax.swing.JPanel hopDongTab;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nguoiChoThueLabel;
    private javax.swing.JPanel nguoiChoThueTab;
    private javax.swing.JLabel nhaTroLabel;
    private javax.swing.JLabel nhaTroLabel1;
    private javax.swing.JLabel phongTroLabel;
    private javax.swing.JPanel phongTroTab;
    private javax.swing.JLabel taiSanLabel;
    private javax.swing.JPanel taiSanTab;
    private javax.swing.JTable tblnhatro;
    // End of variables declaration//GEN-END:variables
}
