/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.NhaTroController;
import java.sql.Date;
import javax.swing.JOptionPane;
import model.NhaTro;

/**
 *
 * @author nm204
 */
public class ThemNhaTro extends javax.swing.JFrame{
    private Home home;
    NhaTroController ntctl;
    NhaTro nhatro = new NhaTro();
    /**
     * Creates new form ThemNhaTro
     */
    public ThemNhaTro(Home home) {
        this.home = home;
        initComponents();
        ntctl = new NhaTroController();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tenTextField = new javax.swing.JTextField();
        diachiTextField = new javax.swing.JTextField();
        soluongTextField = new javax.swing.JTextField();
        ngaybdTextField = new javax.swing.JTextField();
        ttYRadioButton = new javax.swing.JRadioButton();
        ttNRadioButton = new javax.swing.JRadioButton();
        idNVQLTextField = new javax.swing.JTextField();
        backbutton = new javax.swing.JButton();
        thembutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        maNhaTroTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Thêm nhà trọ mới");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhà trọ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Địa chỉ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số lượng phòng");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ngày bắt đầu");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Trạng thái");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID nhân viên quản lý");

        tenTextField.setMinimumSize(new java.awt.Dimension(64, 30));
        tenTextField.setPreferredSize(new java.awt.Dimension(64, 30));
        tenTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenTextFieldActionPerformed(evt);
            }
        });

        diachiTextField.setMinimumSize(new java.awt.Dimension(64, 30));
        diachiTextField.setPreferredSize(new java.awt.Dimension(64, 30));

        soluongTextField.setMinimumSize(new java.awt.Dimension(64, 30));
        soluongTextField.setPreferredSize(new java.awt.Dimension(64, 30));

        ngaybdTextField.setMinimumSize(new java.awt.Dimension(64, 30));
        ngaybdTextField.setPreferredSize(new java.awt.Dimension(64, 30));

        buttonGroup1.add(ttYRadioButton);
        ttYRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ttYRadioButton.setSelected(true);
        ttYRadioButton.setText("Yes");
        ttYRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttYRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(ttNRadioButton);
        ttNRadioButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ttNRadioButton.setText("No");

        idNVQLTextField.setMinimumSize(new java.awt.Dimension(64, 30));
        idNVQLTextField.setPreferredSize(new java.awt.Dimension(64, 30));

        backbutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/back.png"))); // NOI18N
        backbutton.setText("Quay lại");
        backbutton.setPreferredSize(new java.awt.Dimension(120, 35));
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });

        thembutton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        thembutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        thembutton.setText("Thêm");
        thembutton.setPreferredSize(new java.awt.Dimension(120, 35));
        thembutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thembuttonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhà trọ");

        maNhaTroTextField.setMinimumSize(new java.awt.Dimension(64, 30));
        maNhaTroTextField.setPreferredSize(new java.awt.Dimension(64, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(66, 66, 66)
                                    .addComponent(ttYRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ttNRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(40, 40, 40)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(maNhaTroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tenTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                            .addComponent(diachiTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(soluongTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(idNVQLTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(backbutton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel5)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(ngaybdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(thembutton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idNVQLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maNhaTroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tenTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diachiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soluongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ttYRadioButton)
                            .addComponent(ttNRadioButton))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngaybdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(thembutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ttYRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttYRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttYRadioButtonActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    private void thembuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thembuttonActionPerformed
        // Kiểm tra mã nhà trọ
        String maNhaTro = maNhaTroTextField.getText().trim();
        if (maNhaTro.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Mã nhà trọ không được để trống.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nhatro.setMaNhaTro(maNhaTro);

        // Kiểm tra tên nhà trọ
        String tenNhaTro = tenTextField.getText().trim();
        if (tenNhaTro.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tên nhà trọ không được để trống.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nhatro.setTenNhaTro(tenNhaTro);

        // Kiểm tra địa chỉ
        String diaChi = diachiTextField.getText().trim();
        if (diaChi.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Địa chỉ không được để trống.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nhatro.setDiaChi(diaChi);

        // Kiểm tra số lượng phòng
        String soLuongPhongText = soluongTextField.getText().trim();
        int soLuongPhong;
        try {
            soLuongPhong = Integer.parseInt(soLuongPhongText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Số lượng phòng phải là một số nguyên.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nhatro.setSoLuongPhong(soLuongPhong);

        // Kiểm tra ngày bắt đầu
        String ngayBatDauText = ngaybdTextField.getText().trim();
        Date ngayBatDau;
        try {
            ngayBatDau = Date.valueOf(ngayBatDauText);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(null, "Ngày bắt đầu không hợp lệ. Định dạng phải là YYYY-MM-DD.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nhatro.setNgayBatDau(ngayBatDau);

        // Kiểm tra trạng thái
        String status = "";
        if (ttYRadioButton.isSelected()) {
            status = "Y";
        } else if (ttNRadioButton.isSelected()) {
            status = "N";
        } else {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn trạng thái.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nhatro.setTrangThai(status);

        // Kiểm tra ID nhân viên quản lý
        String idNhanVienQuanLyText = idNVQLTextField.getText().trim();
        int idNhanVienQuanLy;
        try {
            idNhanVienQuanLy = Integer.parseInt(idNhanVienQuanLyText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "ID nhân viên quản lý phải là một số nguyên.", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
            return;
        }
        nhatro.setIdNhanVienQuanLy(idNhanVienQuanLy);

        // Thêm đối tượng nhà trọ vào cơ sở dữ liệu
        try {
            ntctl.Insert(nhatro);
            JOptionPane.showMessageDialog(null, "Thêm nhà trọ thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Có lỗi xảy ra khi thêm nhà trọ: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_thembuttonActionPerformed

    private void tenTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tenTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField diachiTextField;
    private javax.swing.JTextField idNVQLTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField maNhaTroTextField;
    private javax.swing.JTextField ngaybdTextField;
    private javax.swing.JTextField soluongTextField;
    private javax.swing.JTextField tenTextField;
    private javax.swing.JButton thembutton;
    private javax.swing.JRadioButton ttNRadioButton;
    private javax.swing.JRadioButton ttYRadioButton;
    // End of variables declaration//GEN-END:variables
}
